CREATE TABLE npa_blacklist (
    npa		SMALLINT NOT NULL,
    PRIMARY KEY (npa)
);
INSERT INTO npa_blacklist VALUES('242');
INSERT INTO npa_blacklist VALUES('246');
INSERT INTO npa_blacklist VALUES('264');
INSERT INTO npa_blacklist VALUES('268');
INSERT INTO npa_blacklist VALUES('284');
INSERT INTO npa_blacklist VALUES('340');
INSERT INTO npa_blacklist VALUES('345');
INSERT INTO npa_blacklist VALUES('441');
INSERT INTO npa_blacklist VALUES('473');
INSERT INTO npa_blacklist VALUES('649');
INSERT INTO npa_blacklist VALUES('658');
INSERT INTO npa_blacklist VALUES('664');
INSERT INTO npa_blacklist VALUES('721');
INSERT INTO npa_blacklist VALUES('758');
INSERT INTO npa_blacklist VALUES('767');
INSERT INTO npa_blacklist VALUES('784');
INSERT INTO npa_blacklist VALUES('787');
INSERT INTO npa_blacklist VALUES('809');
INSERT INTO npa_blacklist VALUES('829');
INSERT INTO npa_blacklist VALUES('849');
INSERT INTO npa_blacklist VALUES('868');
INSERT INTO npa_blacklist VALUES('869');
INSERT INTO npa_blacklist VALUES('876');
INSERT INTO npa_blacklist VALUES('939');
INSERT INTO npa_blacklist VALUES('907');