-- migration tables

CREATE TABLE "public".mig_phone (
    id                  SERIAL NOT NULL,
    account_id          INT DEFAULT NULL,
    customer_id         INT DEFAULT NULL,
    session_id          varchar(32) DEFAULT NULL,
    cfa_number_id       INT DEFAULT NULL,
    msg                 varchar(250) DEFAULT NULL,
    status              varchar(16) DEFAULT NULL,
    created             timestamp(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE "public".mig_account_features (
    "id"                    SERIAL NOT NULL,
    session_id              varchar(32) DEFAULT NULL,
    account_name            varchar(255) DEFAULT NULL,
--    account_id              serial NOT NULL,
    company_type_industry   varchar(32) DEFAULT NULL,
    billing_entity          varchar(32) DEFAULT NULL,
    customer_support        varchar(32) DEFAULT NULL,
    account_status          varchar(32) DEFAULT NULL,
    invoice_recipient       varchar(32) DEFAULT NULL,
    billing_process         varchar(32) DEFAULT NULL,
    billing_period          varchar(32) DEFAULT NULL,
    billing_method          varchar(32) DEFAULT NULL,
    billing_start_date      varchar(64) DEFAULT NULL,
    last_invoice_date       varchar(64) DEFAULT NULL,
    call_duration_method    varchar(32) DEFAULT NULL,
    spm_package             varchar(32) DEFAULT NULL,
    main_contact_name       varchar(255) DEFAULT NULL,
    title                   varchar(255) DEFAULT NULL,
    address_1               varchar(255) DEFAULT NULL,
    address_2               varchar(255) DEFAULT NULL,
    city                    varchar(45) DEFAULT NULL,
    state_province          varchar(45) DEFAULT NULL,
    zip                     varchar(45) DEFAULT NULL,
    zip4                    varchar(45) DEFAULT NULL,
    country                 varchar(45) DEFAULT NULL,
    phone                   varchar(45) DEFAULT NULL,
    extension               varchar(32) DEFAULT NULL,
    fax                     varchar(45) DEFAULT NULL,
    email                   varchar(255) DEFAULT NULL,
    billing_contact_company_name varchar(255) DEFAULT NULL,
    name                    varchar(255) DEFAULT NULL,
    title_1                 varchar(255) DEFAULT NULL,
    address_1_1             varchar(255) DEFAULT NULL,
    address_2_1             varchar(255) DEFAULT NULL,
    city_1                  varchar(45) DEFAULT NULL,
    state_province_1        varchar(45) DEFAULT NULL,
    zip_1                   varchar(45) DEFAULT NULL,
    zip4_1                  varchar(45) DEFAULT NULL,
    country_1               varchar(45) DEFAULT NULL,
    phone_1                 varchar(45) DEFAULT NULL,
    extension_1             varchar(32) DEFAULT NULL,
    fax_1                   varchar(45) DEFAULT NULL,
    email_1                 varchar(255) DEFAULT NULL,
    support_phone_number    varchar(45) DEFAULT NULL,
    support_extension       varchar(32) DEFAULT NULL,
    support_email           varchar(255) DEFAULT NULL,
    private_label_branding  varchar(32) DEFAULT NULL,
    branding_key            varchar(32) DEFAULT NULL,
    customer_code_label     varchar(32) DEFAULT NULL,
    logout_redirect_url     varchar(255) DEFAULT NULL,
    email_callreview_by_name varchar(255) DEFAULT NULL,
    dls_from_name           varchar(255) DEFAULT NULL,
    dls_from_email          varchar(255) DEFAULT NULL,
    dls_email_subject       varchar(255) DEFAULT NULL,
    scheduled_reports_from_name varchar(255) DEFAULT NULL,
    scheduled_reports_from_email varchar(255) DEFAULT NULL,
    scheduled_reports_subject   varchar(255) DEFAULT NULL,
    scheduled_reports_base_url  varchar(255) DEFAULT NULL,
    rtn_email_from_name     varchar(255) DEFAULT NULL,
    rtn_email_from_email    varchar(255) DEFAULT NULL,
    rtn_email_subject       varchar(255) DEFAULT NULL,
    contact_code            varchar(32) DEFAULT NULL,
    ftp_cd_data_feed        varchar(32) DEFAULT NULL,
    call_center_routing     varchar(32) DEFAULT NULL,
    geo_routing             varchar(32) DEFAULT NULL,
    extension_routing       varchar(32) DEFAULT NULL,
    user_creation_at_site_level varchar(32) DEFAULT NULL,
    mrs_user_creation       varchar(32) DEFAULT NULL,
    routing_restriction     varchar(32) DEFAULT NULL,
    callmenow               varchar(32) DEFAULT NULL,
    lead2call               varchar(32) DEFAULT NULL,
    ireview___speed_score   varchar(32) DEFAULT NULL,
    leadmanager             varchar(32) DEFAULT NULL,
    outbound_notification   varchar(32) DEFAULT NULL,
    default_scheduled_reports varchar(32) DEFAULT NULL,
    allow_tracking_number   varchar(32) DEFAULT NULL,
    web___dng               varchar(32) DEFAULT NULL,
    rtn_call_length         varchar(32) DEFAULT NULL,
    rtn_email               varchar(32) DEFAULT NULL,
    rtn_email_type          varchar(32) DEFAULT NULL,
    maximum_number_of_templates INT DEFAULT NULL,
    rtn_email_template      varchar(255) DEFAULT NULL,
    rtn_post                varchar(32) DEFAULT NULL,
    rtn_post_type           varchar(32) DEFAULT NULL,
    rtn_conten_type_header  varchar(255) DEFAULT NULL,
    rtn_post_template       varchar(255) DEFAULT NULL,
    rtn_post_url            varchar(255) DEFAULT NULL,
    employee_entry          varchar(32) DEFAULT NULL,
    voicemail               varchar(32) DEFAULT NULL,
    rna_rings_no_answer     INT DEFAULT NULL,
    call_review             varchar(32) DEFAULT NULL,
    disclaimer_language     varchar(32) DEFAULT NULL,
    mailmaster              varchar(32) DEFAULT NULL,
    consumer_greeting       varchar(32) DEFAULT NULL,
    whisper                 varchar(32) DEFAULT NULL,
    whisper_type            varchar(255) DEFAULT NULL,
    whisper_file            varchar(255) DEFAULT NULL,
    outbound_calling_1      varchar(32) DEFAULT NULL,
    campaign_length         INT DEFAULT NULL,
    referral_length         INT DEFAULT NULL,
    auto_extend_campaigns   varchar(32) DEFAULT NULL,
    call_processing         varchar(32) DEFAULT NULL,
    tpa_reporting           varchar(32) DEFAULT NULL,
    tpa_processing          varchar(32) DEFAULT NULL,
    leadScore_processing    varchar(32) DEFAULT NULL,
    leadScore_reporting     varchar(32) DEFAULT NULL,
    dls                     varchar(32) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE "public".mig_campaign (
    id                  serial NOT NULL,
    account_id          INT DEFAULT NULL,
    customer_id         INT DEFAULT NULL,
    session_id          varchar(32) DEFAULT NULL,
    cs_campaign_id      varchar(32) DEFAULT NULL,
    cfa_campaign_id     INT DEFAULT NULL,
    msg                 varchar(250) DEFAULT NULL,
    status              varchar(16) DEFAULT NULL,
    created             timestamp(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE "public".mig_campaign_provisioning (
    "id"                    serial NOT NULL,
    session_id              varchar(32) DEFAULT NULL,
    status                  varchar(16) DEFAULT NULL,
    account_name            varchar(255) DEFAULT NULL,
--    account_id              serial NOT NULL,
    customer_code           INT DEFAULT NULL,
    customer_name           varchar(64) DEFAULT NULL,
    customer_id             INT DEFAULT NULL,
    customer_status         varchar(32) DEFAULT NULL,
    campaign_id             INT DEFAULT NULL,
    campaign_name           varchar(255) DEFAULT NULL,
    ad_source_s             varchar(64) DEFAULT NULL,
    start_date              varchar(64) DEFAULT NULL,
    end_date                varchar(64) DEFAULT NULL,
    referral_end_date       varchar(64) DEFAULT NULL,
    tracking_number         varchar(45) DEFAULT NULL,
    carrier                 varchar(64) DEFAULT NULL,
    did_type                varchar(32) DEFAULT NULL,
    target_number           varchar(45) DEFAULT NULL,
    time_zone               varchar(32) DEFAULT NULL,
    did_status              varchar(32) DEFAULT NULL,
    disconnected            varchar(32) DEFAULT NULL,
    campaign_status         varchar(32) DEFAULT NULL,
    ad_cost                 varchar(64) DEFAULT NULL,
    ad_cost_basis           varchar(45) DEFAULT NULL,
    consumer_greeting       varchar(32) DEFAULT NULL,
    consumer_greeting_file  varchar(255) DEFAULT NULL,
    whisper_greeting        varchar(255) DEFAULT NULL,
    whisper_file            varchar(255) DEFAULT NULL,
    whisper_type            varchar(64) DEFAULT NULL,
    call_review             varchar(32) DEFAULT NULL,
    disclaimer_language     varchar(32) DEFAULT NULL,
    vm_rna                  varchar(32) DEFAULT NULL,
    employee_code_entry     varchar(32) DEFAULT NULL,
    mailmaster              varchar(32) DEFAULT NULL,
    send_rtn_email_1        varchar(32) DEFAULT NULL,
    rtn_email_1_timing      varchar(64) DEFAULT NULL,
    rtn_email_1_template    varchar(64) DEFAULT NULL,
    rtn_email_1_address_es  varchar(255) DEFAULT NULL,
    send_rtn_email_2        varchar(255) DEFAULT NULL,
    rtn_email_2_timing      varchar(64) DEFAULT NULL,
    rtn_email_2_template    varchar(64) DEFAULT NULL,
    rtn_email_2_address_es  varchar(255) DEFAULT NULL,
    send_rtn_email_3        varchar(255) DEFAULT NULL,
    rtn_email_3_timing      varchar(64) DEFAULT NULL,
    rtn_email_3_template    varchar(64) DEFAULT NULL,
    rtn_email_3_address_es  varchar(255) DEFAULT NULL,
    send_http_post          varchar(32) DEFAULT NULL,
    rtn_post_url            varchar(255) DEFAULT NULL,
    rtn_http_template       varchar(64) DEFAULT NULL,
    leadscore               varchar(32) DEFAULT NULL,
    lead2call_enabled       varchar(32) DEFAULT NULL,
    callmenow_enabled       varchar(32) DEFAULT NULL,
    vanity_regions          INT DEFAULT NULL,
    geo_regions             INT DEFAULT NULL,
    level_1_extensions      INT DEFAULT NULL,
    tod_routings            INT DEFAULT NULL,
    overflows               INT DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE "public".mig_customer_features (
    "id"                    serial NOT NULL,
    "session_id"            varchar(32) DEFAULT NULL,
    "account_name"          varchar(255) DEFAULT NULL,
    "account_id"            INT DEFAULT NULL,
    "location___customer_name" varchar(255) DEFAULT NULL,
    "location___customer_code" varchar(255) DEFAULT NULL,
    "customer_id"           INT DEFAULT NULL,
    "customer_status"       varchar(64) DEFAULT NULL,
    "default_target_number" varchar(64) DEFAULT NULL,
    "spm_package"           varchar(32) DEFAULT NULL,
    "primary_contact_name"  varchar(255) DEFAULT NULL,
    "title"                 varchar(64) DEFAULT NULL,
    "address_1"             varchar(255) DEFAULT NULL,
    "address_2"             varchar(255) DEFAULT NULL,
    "city"                  varchar(64) DEFAULT NULL,
    "state_province"        varchar(64) DEFAULT NULL,
    "zip"                   varchar(64) DEFAULT NULL,
    "zip4"                  varchar(64) DEFAULT NULL,
    "country"               varchar(64) DEFAULT NULL,
    "phone"                 varchar(64) DEFAULT NULL,
    "extension"             varchar(64) DEFAULT NULL,
    "fax"                   varchar(64) DEFAULT NULL,
    "email"                 varchar(255) DEFAULT NULL,
    "method"                varchar(64) DEFAULT NULL,
    "billing_period"        varchar(32) DEFAULT NULL,
    "billing_process"       varchar(32) DEFAULT NULL,
    "billing_start_date"    varchar(64) DEFAULT NULL,
    "last_invoice_date"     varchar(64) DEFAULT NULL,
    "billing_contact_company_name" varchar(255) DEFAULT NULL,
    "name"                  varchar(255) DEFAULT NULL,
    "title-1"               varchar(64) DEFAULT NULL,
    "address_1-1"           varchar(255) DEFAULT NULL,
    "address_2-1"           varchar(255) DEFAULT NULL,
    "city-1"                varchar(64) DEFAULT NULL,
    "state_province-1"      varchar(64) DEFAULT NULL,
    "zip-1"                 varchar(64) DEFAULT NULL,
    "zip4-1"                varchar(64) DEFAULT NULL,
    "country-1"             varchar(64) DEFAULT NULL,
    "phone-1"               varchar(64) DEFAULT NULL,
    "extension-1"           varchar(64) DEFAULT NULL,
    "fax-1"                 varchar(64) DEFAULT NULL,
    "email-1"               varchar(255) DEFAULT NULL,
    "support_phone_number"  varchar(64) DEFAULT NULL,
    "support_extension"     varchar(64) DEFAULT NULL,
    "support_email"         varchar(255) DEFAULT NULL,
    "daily_leads__dls_report" varchar(32) DEFAULT NULL,
    "auto_extend_campaigns" varchar(32) DEFAULT NULL,
    "auto_extend_length"    INT DEFAULT NULL,
    "ireview___speed_score" varchar(32) DEFAULT NULL,
    "caller_id_number"      varchar(64) DEFAULT NULL,
    "tpa_processing"        varchar(32) DEFAULT NULL,
    "call_processing"       varchar(32) DEFAULT NULL,
    "leadscore_rtn_email"   varchar(32) DEFAULT NULL,
    "leadscore_rtn_email_template" varchar(64) DEFAULT NULL,
    "leadscore_rtn_post"    varchar(32) DEFAULT NULL,
    "leadscore_rtn_post_template"   varchar(64) DEFAULT NULL,
    "leadscore_rtn_post_url"        varchar(255) DEFAULT NULL,
    "call_processing_rtn_post"      varchar(32) DEFAULT NULL,
    "leadscore_rtn_post_template-1" varchar(64) DEFAULT NULL,
    "leadscore_rtn_post_url-1"      varchar(255) DEFAULT NULL,
    "employee_name"         varchar(255) DEFAULT NULL
    PRIMARY KEY (id)
);

CREATE TABLE "public".mig_group (
    id                  serial NOT NULL,
    account_id          INT DEFAULT NULL,
    customer_id         INT DEFAULT NULL,
    session_id          varchar(32) DEFAULT NULL,
    cfa_ouid            INT DEFAULT NULL,
    msg                 varchar(250) DEFAULT NULL,
    status              varchar(16) DEFAULT NULL,
    created             timestamp(0) WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

CREATE TABLE "public".mig_logs (
    id                  serial NOT NULL,
    line                int,
    session_id          varchar(32) DEFAULT NULL,
    type                varchar(128) DEFAULT NULL,
    msg                 varchar(250) DEFAULT NULL,
    created             timestamp(0) WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

CREATE TABLE "public".mig_route (
    id                  serial NOT NULL,
    account_id          INT DEFAULT NULL,
    customer_id         INT DEFAULT NULL,
    session_id          varchar(32) DEFAULT NULL,
    cs_campaign_id      varchar(32) DEFAULT NULL,
    cfa_route_id        INT DEFAULT NULL,
    msg                 varchar(250) DEFAULT NULL,
    status              varchar(16) DEFAULT NULL,
    created             timestamp(0) WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

CREATE TABLE public.org_unit_number (
	org_unit_id         int NOT NULL,
	phone_number_id     int NOT NULL,
	date_assigned       timestamp(0) WITHOUT TIME ZONE NOT NULL DEFAULT now(),
	date_removed        timestamp(0) WITHOUT TIME ZONE DEFAULT NULL
);
