CREATE TABLE report_source (
    rs_id bigserial NOT NULL,
    source character varying(255),
	campaign_id integer,
    rs_date timestamp with time Zone,
    rs_grouping_key character varying(255),
    rs_grouping_value character varying(2048),
    rs_json json
);

ALTER TABLE ONLY report_source
    ADD CONSTRAINT report_source_pkey PRIMARY KEY (rs_id);
	
ALTER TABLE ONLY report_source
    ADD CONSTRAINT report_source_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaign(campaign_id) ON UPDATE CASCADE ON DELETE CASCADE;
	
ALTER TABLE channel ADD COLUMN search_string VARCHAR(128);

INSERT INTO channel (category,sub_category,channel_created,channel_status,cat_combo,search_string)
	VALUES ('Google','Paid',NOW(),'active','Google: Paid','google'),
	('Google','Paid-Ad Ext.',NOW(),'active','Google: Paid-Ad Ext.','google'),
	('Google','Display',NOW(),'active','Google: Display','google'),
	('Google','Organic',NOW(),'active','Google: Organic','google'),
	('Bing','Paid',NOW(),'active','Bing: Paid','bing'),
	('Bing','Paid-Ad Ext.',NOW(),'active','Bing: Paid-Ad Ext.','bing'),
	('Bing','Display',NOW(),'active','Bing: Display','bing'),
	('Bing','Organic',NOW(),'active','Bing: Organic','bing'),
	('Yahoo','Paid',NOW(),'active','Yahoo: Paid','yahoo'),
	('Yahoo','Display',NOW(),'active','Yahoo: Display','yahoo'),
	('Yahoo','Organic',NOW(),'active','Yahoo: Organic','yahoo'),
	('Facebook','Social',NOW(),'active','Facebook: Social','facebook'),
	('Facebook','Paid',NOW(),'active','Facebook: Paid','facebook'),
	('Facebook','Display',NOW(),'active','Facebook: Display','facebook'),
	('Google+','Social',NOW(),'active','Google+: Social','plus.google'),
	('Linkedin','Social',NOW(),'active','Linkedin: Social','linkedin'),
	('Linkedin','Paid',NOW(),'active','Linkedin: Paid','linkedin'),
	('Twitter','Social',NOW(),'active','Twitter: Social','twitter');
	
INSERT INTO report_definition_object (rdo_id, rdo_report_id, rdo_report_name, data)
	VALUES (6, 6, 'Sources', '{

    "chartobjs":[
        {
            "id":0,
            "name":"Source Call Volume",
            "type":"row",
            "dimension":"source",
            "dimensiontype":"none",
            "interval":"none",
            "group":"total_calls",
            "grouptype":"sum",
            "sort":"none",
            "top":"top",
            "top_value":"10",
            "width":300,
            "height":400,
            "maximize_width":0,
            "maximize_height":0
        },
        {
            "id":1,
            "name":"Total Calls",
            "type":"number",
            "dimension":"call_group",
            "dimensiontype":"none",
            "interval":"none",
            "group":"total_calls",
            "grouptype":"reduce",
            "sort":"none",
            "top":"none",
            "top_value":"none",
            "format":",.0f"
        },
        {
            "id":2,
            "name":"Total Leads",
            "type":"number",
            "dimension":"call_group",
            "dimensiontype":"none",
            "interval":"none",
            "group":"lead_count",
            "grouptype":"reduce",
            "sort":"",
            "top":"none",
            "top_value":"",
            "format":",.0f"
        },
        {
            "id":3,
            "name":"% Leads of Calls",
            "type":"number",
            "dimension":"call_group",
            "dimensiontype":"none",
            "interval":"none",
            "group":"lead_count",
            "grouptype":"reduce",
            "sort":"",
            "top":"none",
            "top_value":"",
            "averageDenominator":"total_calls",
            "format":",%"
        },
        {
            "id":4,
            "name":"Avg. Lead Qual.",
            "type":"number",
            "dimension":"call_group",
            "dimensiontype":"none",
            "interval":"none",
            "group":"lead_sum",
            "grouptype":"reduce",
            "sort":"none",
            "top":"none",
            "top_value":"none",
            "averageDenominator":"total_calls",
            "format":",.0f"
        },
        {
            "id":5,
            "name":"Conversion",
            "type":"number",
            "dimension":"call_group",
            "dimensiontype":"none",
            "interval":"none",
            "group":"conversion_count",
            "grouptype":"reduce",
            "sort":"none",
            "top":"none",
            "top_value":"none",
            "format":",.0f"
        },
        {
            "id":6,
            "name":"Conversion %",
            "type":"number",
            "dimension":"call_group",
            "dimensiontype":"none",
            "interval":"none",
            "group":"conversion_count",
            "grouptype":"reduce",
            "averageDenominator":"total_calls",
            "sort":"",
            "top":"none",
            "top_value":"",
            "percentage":true,
            "format":",%"
        },
        {
            "id":7,
            "name":"Avg Duration (seconds)",
            "type":"number",
            "dimension":"call_group",
            "dimensiontype":"none",
            "interval":"none",
            "group":"duration_sum",
            "grouptype":"reduce",
            "averageDenominator":"total_calls",
            "sort":"",
            "top":"none",
            "top_value":"",
            "format":",.0f"
        },
        {
            "id":8,
            "name":"Unique Calls",
            "type":"number",
            "dimension":"call_group",
            "dimensiontype":"none",
            "interval":"none",
            "group":"unique_calls",
            "grouptype":"reduce",
            "averageDenominator":false,
            "sort":"",
            "top":"none",
            "top_value":"",
            "format":",.0f"
        },
        {
            "id":9,
            "name":"Calls Over Time",
            "type":"bar2",
            "dimensiontype":"time",
            "interval":"day",
            "dimension":"date",
            "group":"total_calls",
            "grouptype":"sum",
            "sort":"",
            "top":"none",
            "top_value":"",
            "width":900,
            "height":88
        },
        {
            "id":10,
            "name":"Calls By Day of Week",
            "dimensiontype":"time",
            "interval":"weekzer",
            "grouptype":"dayWeekReduce",
            "type":"row2",
            "dimension":"date",
            "group":"total_calls",
            "sort":"",
            "top":"none",
            "top_value":"",
            "width":300,
            "height":297
        },
        {
            "id":11,
            "name":"Conversion over Time",
            "type":"timeline",
            "dimension":"date",
            "dimensiontype":"time",
            "interval":"day",
            "group":"conversion_percent",
            "grouptype":"reducePercent",
            "sort":"",
            "top":"none",
            "top_value":"",
            "width":400,
            "height":277
        },
        {
            "id":12,
            "name":"Teh Data Table",
            "type":"datagrid2",
            "dimension":"source",
            "dimensiontype":"none",
            "interval":"none",
            "group":"total_calls",
            "grouptype":"reduce",
            "averageDenominator":"total_calls",
            "sort":"",
            "top":"none",
            "top_value":"",
            "width":698,
            "height":330
        },
        {
            "id":13,
            "name":"Call Volume by Group",
            "type":"row",
            "dimension":"source",
            "dimensiontype":"none",
            "interval":"none",
            "group":"total_calls",
            "grouptype":"sum",
            "sort":"",
            "top":"none",
            "top_value":"",
            "width":570,
            "height":770
        },
        {
            "id":21,
            "name":"% Answered",
            "type":"number",
            "dimension":"source",
            "dimensiontype":"none",
            "interval":"none",
            "group":"total_answered",
            "grouptype":"reduce",
            "averageDenominator":"total_calls",
            "sort":"",
            "top":"none",
            "top_value":"",
            "maximize_width":0,
            "maximize_height":0,
            "format":",%"
        },
        {
            "id":22,
            "name":"Calls Over Time",
            "type":"bar2",
            "dimension":"date",
            "dimensiontype":"time",
            "interval":"day",
            "group":"total_calls",
            "grouptype":"sum",
            "sort":"",
            "top":"none",
            "top_value":"",
            "width":400,
            "height":300
        },
        {
            "id":23,
            "name":"Data Table",
            "type":"datagrid",
            "dimension":"source",
            "dimensiontype":"none",
            "interval":"none",
            "group":"total_calls",
            "grouptype":"sum",
            "sort":"",
            "top":"none",
            "top_value":"",
            "x":432,
            "y":580,
            "width":698,
            "height":330,
            "maximize_width":0,
            "maximize_height":0
        }
    ]

}');
