
INSERT INTO component 
(component_id,component_name, component_desc) 
VALUES (133,'Additional Tracking Number: Monthly Cqm', ''),
(134,'Additional Local Tracking Number: Annual Cqm', ''),
(135,'Additional Tracking Number Cqm', ''),
(136,'Minute Blocks Monthly: 500 Cqm', ''),
(137,'Additional Basic User: Monthly Cqm', ''),
(138,'Convirza Reseller Minutes Cqm', ''),
(139,'Tracking Numbers Cqm', ''),
(140,'Minutes Cqm', ''),
(141,'CFA user Cqm', ''),
(142,'Additional Pro User: Monthly Cqm', ''),
(143,'Additional Performance User Cqm', ''),
(144,'Usage Minutes Cqm', ''),
(145,'Additional TPS User: Monthly Cqm', ''),
(146,'All Call Upload Cqm', ''),
(147,'Convirza Basic: Monthly Cqm',''),
(148,'Convirza Basic: Annual Cqm',''),
(149,'Additional Basic User: Annual Cqm',''),
(150,'Convirza Lite: Monthly Cqm',''),
(151,'Convirza Pro: Monthly Cqm',''),
(152,'Additional Pro User: Annual Cqm',''),
(153,'Convirza Pro: Annual Cqm',''),
(154,'Additional Enterprise User: Monthly Cqm',''),
(155,'Convirza Enterprise: Monthly Cqm',''),
(156,'Convirza Reseller Number Cqm',''),
(157,'Performance Cqm',''),
(158,'Discount Cqm',''),
(159,'Additional Value User Cqm',''),
(160,'Value Cqm',''),
(161,'Additional Value Plan Tracking Number Cqm',''),
(162,'Additional Unlimited Plan Tracking Number: 200 Cqm',''),
(163,'Convirza Unlimited Cqm',''),
(164,'Additional Unlimited User: Monthly Cqm',''),
(165,'Maximizer Cqm',''),
(166,'Optimizer Cqm',''),
(167,'Monthly Platform Fee Cqm',''),
(168,'Platform Fee Cqm',''),
(169,'PCI Monthly Cqm', ''),
(170,'PCI Setup Fee Cqm',''),
(171,'Monthly Cqm',''),
(172,'Performance Cqm',''),
(173,'Discount Cqm',''),
(174,'Additional Minutes Cqm', ''),
(175,'Optimizer/Maximizer User Cqm', ''),
(176,'Basic User: Monthly Cqm', ''),      
(177,'Pro User: Monthly Cqm', ''),
(178,'Enterprise User: Monthly Cqm', ''),
(179,'Basic User: Annual Cqm', ''),
(180,'Pro User: Annual Cqm', ''),
(181,'Enterprise User: Annual Cqm', ''),
(182,'Tracking Number: Monthly Cqm', ''),
(183,'Toll-Free Number: Monthly Cqm', ''),
(184,'Minute Blocks: Monthly: 500 Cqm', ''),
(185,'ProScore: Monthly Cqm', ''),
(186,'Tracking Number: Annual Cqm', ''),
(187,'Toll-Free Number: Annual Cqm', ''),
(188,'Minute Blocks Annual: 500 Cqm', ''),
(189,'ProScore: Annual Cqm', '6019'),
(190,'LogMyCalls Reseller Number: 100 Cqm', ''),
(191,'LogMyCalls Reseller Number: 200 Cqm', ''),
(192,'LogMyCalls Reseller Number: 0 Cqm', ''),
(193,'ProTag: Monthly Cqm', ''),
(194,'ProTag: Annual Cqm', ''),
(195,'Reseller User: Monthly Cqm', ''),
(196,'LogMyCalls Reseller TF: 100 Cqm', ''),
(197,'LogMyCalls Reseller TF: 0 Cqm', ''),
(198,'LogMyCalls Reseller TF: 200 Cqm', ''),
(199,'LogMyCalls Reseller: Minutes Cqm', ''),
(200,'Performance User Cqm', ''),
(201,'Value User Cqm', ''),
(202,'Unlimited User Cqm', ''),
(203,'LogMyCalls Maximizer Minutes Cqm', '')
(204,'Conversation Analytics Cqm', ''),
(205,'API Call Upload Cqm', ''),
(206,'Value Plan Tracking Number Cqm', ''),
(207,'Unlimited Plan Tracking Number Cqm', ''),
(208,'Maximizer Plan Tracking Number Cqm', ''),
(209,'API Call Analysis Cqm', ''),
(210,'LogMyCalls Advanced Analytics Cqm', ''),
(211,'LogMyCalls Quick Start Cqm', ''),
(212,'Reserve numbers/ number pools Cqm', ''),
(213,'Maximizer Minutes Cqm', '')
