-- adjust org_billing cycle columns to just date
ALTER TABLE org_billing ALTER COLUMN cycle_start SET DATA TYPE DATE;
ALTER TABLE org_billing ALTER COLUMN cycle_end SET DATA TYPE DATE;

ALTER TABLE org_billing ADD COLUMN current_count_start TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE org_billing ADD COLUMN prev_count_start TIMESTAMP WITH TIME ZONE DEFAULT NULL;

ALTER TABLE log_ivr ALTER COLUMN log_date SET DATA TYPE TIMESTAMP(0) WITH TIME ZONE;
ALTER TABLE log_tag ALTER COLUMN log_date SET DATA TYPE TIMESTAMP(0) WITH TIME ZONE;
ALTER TABLE log_billing ALTER COLUMN log_date SET DATA TYPE TIMESTAMP(0) WITH TIME ZONE;

ALTER TABLE org_billing ALTER COLUMN current_count_start SET DATA TYPE TIMESTAMP(0) WITH TIME ZONE;
ALTER TABLE org_billing ALTER COLUMN prev_count_start SET DATA TYPE TIMESTAMP(0) WITH TIME ZONE;
